AplicacionRazor/Pages/Cursos/Crear.cshtml.cs
using AplicacionRazor.modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionRazor.Pages.Cursos
{
    public class CrearModel : PageModel
    {
        private readonly ApplicationDbContext _contexto;

        public CrearModel(ApplicationDbContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty] 
        public  Curso Curso { get; set; }

        [TempData]
        public string Mensaje { get; set; }
        public void OnGet()
        {
        }

        public async Task<IActionResult> OnPost() {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Curso.FechaCreacion = DateTime.Now;
            _contexto.Add(Curso);
            await _contexto.SaveChangesAsync();
            Mensaje = "Curso Creado";
            return RedirectToPage("Index");
        }
    }
}

AplicacionRazor/Pages/Cursos/Editar.cshtml.cs
using AplicacionRazor.modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionRazor.Pages.Cursos
{
    public class EditarModel : PageModel
    {
        private readonly ApplicationDbContext _contexto;

        public EditarModel(ApplicationDbContext contexto)
        {
            _contexto = contexto;
        }

        [BindProperty]
        public Curso Curso { get; set; }
        [TempData]
        public string Mensaje { get; set; }
        public async Task OnGet(int id)
        {
            Curso = await _contexto.Curso.FindAsync(id);
        }

        public async Task<IActionResult> OnPost()
        {
            if (ModelState.IsValid)
            {
                var CurosDesdeBD = await _contexto.Curso.FindAsync(Curso.Id);
                CurosDesdeBD.NombreCurso = Curso.NombreCurso;
                CurosDesdeBD.CantidadClases = Curso.CantidadClases;
                CurosDesdeBD.Precio = Curso.Precio;

                await _contexto.SaveChangesAsync();
                Mensaje = "Curso Editado";
                return RedirectToPage("Index");
            }
            return RedirectToPage();
        }
    }
}

AplicacionRazor/Pages/Cursos/Index.cshtml.cs
using AplicacionRazor.modelos;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using System.Numerics;

namespace AplicacionRazor.Pages.Cursos
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _contexto;

        public IndexModel(ApplicationDbContext contexto)
        {
            _contexto = contexto;   
        }

        [TempData]
        public string Mensaje { get; set; }

        public IEnumerable <Curso> Cursos { get; set; }

        public async Task OnGet()
        {
            Cursos = await _contexto.Curso.ToListAsync();
        }

        public async Task<IActionResult> OnPostBorrar(int Id)
        {
                var Curso = await _contexto.Curso.FindAsync(Id);
                if(Curso == null)
                {
                    return NotFound();
                }

                _contexto.Curso.Remove(Curso);
                await _contexto.SaveChangesAsync();
                Mensaje = "Curso Borrado";
               return RedirectToPage("Index");
        }
    }
}

AplicacionRazor/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace AplicacionRazor.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

AplicacionRazor/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionRazor.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

AplicacionRazor/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace AplicacionRazor.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }

}

AplicacionRazor/Pages/Cursos/Crear.cshtml
@page
@model AplicacionRazor.Pages.Cursos.CrearModel
@{
    ViewData["Title"] = "Crear un nuevo Curso";
}

<div class="card">
    <div class="card-header">
        <h2 class="text-info">Crear un nuevo Curso</h2>
    </div>
    <div class="card-body">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

            <div class="container" style="padding: 20px;">

                <div class="form-group row">
                    <label asp-for="Curso.NombreCurso" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-8">
                        <input asp-for="Curso.NombreCurso" class="form-control" />
                        <span asp-validation-for="Curso.NombreCurso" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <label asp-for="Curso.CantidadClases" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-8">
                        <input asp-for="Curso.CantidadClases" class="form-control" />
                        <span asp-validation-for="Curso.CantidadClases" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <label asp-for="Curso.Precio" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-8">
                        <input asp-for="Curso.Precio" class="form-control" />
                        <span asp-validation-for="Curso.Precio" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Crear</button>
                        <a asp-page="Index" class="btn btn-success ml-2">Volver a la lista</a>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>

AplicacionRazor/Pages/Cursos/Editar.cshtml
@page
@model AplicacionRazor.Pages.Cursos.EditarModel
@{
    ViewData["Title"] = "Editar Curso";
}
<div class="card">
    <div class="card-header">
        <h2 class="text-info">Editar Curso</h2>
    </div>
    <div class="card-body">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger mb-3"></div>

            <input type="hidden" asp-for="Curso.Id" />
            <div class="container" style="padding: 20px;">

                <div class="form-group row">
                    <label asp-for="Curso.NombreCurso" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-8">
                        <input asp-for="Curso.NombreCurso" class="form-control" />
                        <span asp-validation-for="Curso.NombreCurso" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <label asp-for="Curso.CantidadClases" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-8">
                        <input asp-for="Curso.CantidadClases" class="form-control" />
                        <span asp-validation-for="Curso.CantidadClases" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <label asp-for="Curso.Precio" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-8">
                        <input asp-for="Curso.Precio" class="form-control" />
                        <span asp-validation-for="Curso.Precio" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Editar</button>
                        <a asp-page="Index" class="btn btn-success ml-2">Volver a la lista</a>
                    </div>
                </div>

            </div>
        </form>
    </div>
</div>

AplicacionRazor/Pages/Cursos/Index.cshtml
@page
@model AplicacionRazor.Pages.Cursos.IndexModel

@{
    ViewData["Title"] = "Lista de Cursos";
}

@if (Model.Mensaje != null )
{
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
        @Model.Mensaje
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
}

<div class="text-center mb-4">
    Mira nuestros cursos profesionales en: <a href="https://render2web.com/cursos" target="_blank">www.render2web.com/cursos</a>
</div>

<div class="card">
    <div class="card-header">
        <div class="row">
            <div class="col-sm-6">
                <h2 class="text-info">Lista de Cursos</h2>
            </div>
            <div class="col-sm-6 text-right">
                <a asp-page="Crear" class="btn btn-primary">Crear Nuevo Curso</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <form method="post">
        @if (Model.Cursos.Count() > 0)
        {
            <table class="table table-striped table-hover">
                <thead class="thead-light">
                    <tr>
                        <th>
                            @Html.DisplayNameFor(m => m.Cursos.First().Id)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.Cursos.First().NombreCurso)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.Cursos.First().CantidadClases)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.Cursos.First().Precio)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.Cursos.First().FechaCreacion)
                        </th>
                        <th>
                            Acciones
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.Cursos)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(m => item.Id)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.NombreCurso)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.CantidadClases)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.Precio)
                            </td>
                            <td>
                                @Html.DisplayFor(m => item.FechaCreacion)
                            </td>
                            <td>
                                <a asp-route-id="@item.Id" asp-page="Editar" class="btn btn-success btn-sm">Editar</a>
                                <button asp-page-handler="Borrar" asp-route-id="@item.Id" onclick="return confirm('¿Está seguro de querer borrar?')" class="btn btn-danger btn-sm">Borrar</button>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No hay cursos disponibles</p>
        }
        </form>
    </div>
</div>

AplicacionRazor/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <div class="text-center">Mira nuestros cursos profesionales en: <a href="https://render2web.com/cursos">www.render2web.com/cursos</a></div>
</div>

AplicacionRazor/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AplicacionRazor</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AplicacionRazor.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">AplicacionRazor</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Cursos/Index">Administración de Curso</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - AplicacionRazor - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>